version: '3.1'
services:
  db:
    image: mysql
    container_name: task
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data_task:/var/lib/mysql


volumes:
  data_task: